build:linux:x86:20.04:
  image: ${DOCKER_CACHE}/ubuntu:20.04
  stage: build
  before_script:
    - apt-get update && apt-get install -y cmake libdeflate0
  script:
    - cmake -S . -B cmake-build
    - cmake --build cmake-build --config Release --target install -j 8
    - ctest -C Release --test-dir cmake-build --output-on-failure
