variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:linux:x86:20.04:
  image: ${DOCKER_CACHE}/ubuntu:20.04
  stage: build
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y git cmake zlib1g-dev
  script:
    - cmake -S . -B cmake-build
    - cmake --build cmake-build --config Release -j 8
    - ctest -C Release --test-dir cmake-build --output-on-failure
  tags:
    - linux

build:windows:
  stage: build
  script:
    - cmake -S . -B cmake-build -A x64
    - cmake --build cmake-build --config Release -j 8
    - ctest -C Release --test-dir cmake-build --output-on-failure
  tags:
    - win10-gpu
