name: build-minimap2

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            arch: "-A x64"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.22.x'
    - name: Build minimap2
      run: |
        cmake -S . -B cmake-build ${{ matrix.arch }}
        cmake --build cmake-build --config Release -j 4
        ctest -C Release --test-dir cmake-build --output-on-failure
